spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: 127.0.0.1:9092
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
topic:
  name:
    consumer: topico.teste
auto:
  create:
    topics:
      enable: 'true'
server:
  port: '9001'
